- name: install and run nginx
  hosts: 172.31.24.66
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: latest
  - name: nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

