- name: variables
  hosts: localhost
  vars:
    course: devops
    cloud: aws
    technology: ansible
  task:
  - name: print information
    ansible.builtin.debug:
      msg: "Hi, we are learning {{technology}} & {{course}} with {{cloud}}"