- name: variables
  hosts: localhost
  vars_files:
  - vars.yaml
  tasks:
  - name: print information override
    vars:
      technology: "ansible"
    ansible.builtin.debug:
      msg: "Hi, we are learning {{technology}} & {{course}} with {{cloud}}"

  - name: print information
    ansible.builtin.debug:
      msg: "Hi, we are learning {{technology}} & {{course}} with {{cloud}}"