- name: variables
  hosts: localhost
  tasks:
  - name: print information
    ansible.builtin.debug:
      msg: "Hi, we are learning {{tech}} & {{course}} with {{cloud}}"
            "timeings are {{time}}"