- name: variables
  hosts: localhost
  tasks:
  - name: print information
    ansible.builtin.debug:
      msg: "Hi, we are learning {{technology}} as well as {{course}} with {{cloud}} & timings are {{time}}"