- name: variables to check preference
  hosts: localhost
  # vars:
  #   PERSON: "Charan1"
  #   WISHES: "Morning1"
  # vars_files:
  #   - vars.yaml
  # vars_prompt:
  #   - name: PERSON
  #     prompt: please enter person
  #     private: false
  #   - name: WISHES
  #     prompt: please enter wishes
  #     private: false
  tasks: 
  - name: preference
    vars:
      PERSON: "Charan2"
      WISHES: "Morning2"
    ansible.builtin.debug:
      msg: "hello {{PERSON}},Good {{WISHES}}" 

# Preference:
# ------------
  #1.argumesnts
  #2.task
  #3.var_files
  #4.prompt
  #5.play
  #6.inventory