- name: data-types
  hosts: localhost
  vars:
    course: Devops with AWS #string
    Tools: #list
    - linux
    - Shell
    - Ansible
    Experience: #map
      DevOps: 3 #Number
      AWS: 2
      Docker: 1
     Real-project: true #boolean
  tasks:
    - name: print variables
      ansible.builtin.debug:
        msg: "course is {{course}}, {{Tools}} are covered, i am having experience on {{Experience}}, is real project {{Real-project}}"
