- name: check number
  hosts: localhost
  vars_prompt:
  - name: number
    prompt: please enter umber
    private: false
  tasks: 
  - name: number is less than 10
    ansible.builtin.debug:
      msg: "given number {{NUMBER}} is less than 10"
    when: number < 10

  - name: number is greater than 10
    ansible.builtin.debug:
      msg: "given number {{NUMBER}} is greater than 10"
    when: number > 10