- name: default value
  hosts: localhost
  tasks: 
  - name: print default value
    ansible.builtin.debug:
       msg: "Hello {{ course | default('jenkins' )}}"

- name: upper case
  hosts: localhost
  vars: 
    greeting: "Hello, Good Morning"
  tasks: 
  - name: convert the upper case
    ansible.builtin.debug:
      msg: "{{ greeting | upper }}"

- name: lower case
  hosts: localhost
  vars: 
    greeting: "HELLO, GOOD MORNING"
  tasks: 
  - name: convert the lower case
    ansible.builtin.debug:
      msg: "{{greeting | lower}}"

- name: remove  duplicates
  hosts: localhost
  vars:
    numbers: [1,2,2,3,4,5,5,6,7,7,9,9]
  tasks: 
  - name: remove duplicates
    ansible.builtin.debug:
      msg: "{{numbers | unique}}"

- name: print min & max age
  hosts: localhost
  vars:
    ages: [23, 25, 45, 76, 98]
  tasks: 
  - name: min & max ages
    ansible.builtin.debug:
      msg: " min age: {{ages | min}} & max age: {{ages | max}}"

- name: convert dictionary into items/list
  hosts: localhost
  vars:
    my_dict:
      course: Ansible
      trainer: Charan
      duration: 120hr
  tasks: 
  - name: before conversion
    ansible.builtin.debug:
      msg: " Before convert: {{my_dict}}"
  
  - name: after conversion
    ansible.builtin.debug:
      msg: " after convert: {{my_dict | dict2items}}"