- name: default value
  hosts: localhost
  tasks: 
  - name: print default value
    ansible.builtin.debug:
       msg: "Hello {{course | default('jenkins')}}"

- name: upper case
  hosts: localhost
  vars: 
    greeting: "hello, good morning"
  tasks: 
  - name: convert the upper case
  ansible.builtin.debug:
    msg: "{{greeting |  upper}}"