- name: convert items/list into dictionary 
  hosts: localhost
  vars:
    my_dict:
    - {'key': 'course', 'value': 'Ansible'}
    - {'key': 'trainer', 'value': 'Charan'}
    - {'key': 'duration', 'value': '120hr'}
  tasks: 
  - name: before conversion
    ansible.builtin.debug:
      msg: " Before convert: {{my_dict}}"
  
  - name: after conversion
    ansible.builtin.debug:
      msg: " after convert: {{my_dict | items2dict}}"